### ISSUE TITLE
Allow to use port 80 without enforcing https for testing.

### ISSUE THREAD

**Issue by mbroz** [crocs-muni/SED-Storage-Visualiser#1]
The code currently requires reverse https proxy, flask server force to use https by 
app.after_request headers.

For testing it is quite problematic, though (it wil lload only html page with no data).

There should be an option how to allow it for debugging or localhost only testing...

Just FYI @matszabo

**Comment by matszabo** [comment]
I agree, made a pull request to address the issue.
